// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_DCgleZSuoe5171v8n6HOR4kzpK3PQ4',
    appId: '1:1054066711488:web:15fd0cb3fa62b8c1950625',
    messagingSenderId: '1054066711488',
    projectId: 'wholeness-c7dae',
    authDomain: 'wholeness-c7dae.firebaseapp.com',
    storageBucket: 'wholeness-c7dae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiv6nxMh7VANIGy6vI_FIlb_QS5TmPMjM',
    appId: '1:1054066711488:android:7ebbdf267e104b17950625',
    messagingSenderId: '1054066711488',
    projectId: 'wholeness-c7dae',
    storageBucket: 'wholeness-c7dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8a3zBqoijVdp1nDuBvUs5D9FOiZrNnM',
    appId: '1:1054066711488:ios:a4eea5a1f76b68c1950625',
    messagingSenderId: '1054066711488',
    projectId: 'wholeness-c7dae',
    storageBucket: 'wholeness-c7dae.appspot.com',
    iosClientId: '1054066711488-kpu3ipja01moq02eijc30qiuiovi7c9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.wholeness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8a3zBqoijVdp1nDuBvUs5D9FOiZrNnM',
    appId: '1:1054066711488:ios:a4eea5a1f76b68c1950625',
    messagingSenderId: '1054066711488',
    projectId: 'wholeness-c7dae',
    storageBucket: 'wholeness-c7dae.appspot.com',
    iosClientId: '1054066711488-kpu3ipja01moq02eijc30qiuiovi7c9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.wholeness',
  );
}
